version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: ls
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make ci
