version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: ls
      - run: cd Sample/DTL/Shape/
      - run: g++ MazeDig.cpp -Wall -Wextra -O2 -march=native -I../../../include/ -std=c++11
